name: multisig_coordinator
description: A coordinator for creating shared multisignature Hierarchical Deterministic (HD) wallets according to BIP-0048.
version: 0.0.2
repository: https://github.com/cypherstack/multisig_coordinator

environment:
  sdk: ^3.5.4

dependencies:
  coinlib: ^2.2.0
  bip48: ^0.0.3

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
